name: Build XMRig for Raspberry Pi 5 (ARMv8-A)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [arm64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git libuv1-dev libssl-dev libhwloc-dev libcurl4-openssl-dev automake autoconf libtool

      - name: Clone the XMRig Repository
        run: |
          git clone https://github.com/JarzaCode/xmrigCC-donateless.git
          cd xmrigCC-donateless

      - name: Build XMRig for ARMv8-A (Raspberry Pi 5)
        run: |
          cd xmrigCC-donateless
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DARMV8=ON \
            -DNEON=ON \
            -DOPENCL=OFF \
            -DCUDA=OFF \
            -DCMAKE_CXX_FLAGS="-mcpu=cortex-a76 -mtune=cortex-a76 -mfpu=neon-fp-armv8 -march=armv8-a -O3"
          make -j$(nproc)

      - name: Package the binary
        run: |
          mkdir -p output
          cp build/xmrig* output/
          tar -czvf xmrig-rpi5-arm64.tar.gz -C output .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: xmrig-rpi5-arm64
          path: xmrig-rpi5-arm64.tar.gz
